import React from "react";
import { useParams } from "react-router-dom";
import { useTranslation } from "react-i18next";
import StockProductAdminSection from "./components/products/StockProductAdminSection";
import { useStockProductRouteProps } from "./hooks/useStockProductRouteProps";

const CATEGORY_CONFIG = {
  processors: {
    categoryKey: "processors",
    itemsPropName: "processors",
    activeMenuValue: "Processors",
    categoryBrandMapping: { 18: "AMD", 19: "Intel" },
    validCategoryIds: [18, 19],
    titleKey: "admin.danh_sch_b_vi",
    titleDefault: "CPU",
    searchPlaceholderKey: "admin.tm_kim_b_vi",
    searchPlaceholderDefault: "Tim CPU...",
    emptyKey: "admin.khng_tm_thy_b",
    emptyDefault: "Khong co CPU",
    noMatchKey: "remaining.no_processor_match",
    noMatchDefault: "Khong khop",
    formAddTitleKey: "admin.processor_add",
    formAddTitleDefault: "Them CPU",
    formEditTitleKey: "admin.processor_edit",
    formEditTitleDefault: "Sua CPU",
  },
  ram: {
    categoryKey: "ram",
    itemsPropName: "ram",
    activeMenuValue: "RAM",
    categoryBrandMapping: { 30: "Kingston", 31: "Corsair", 32: "PNY" },
    validCategoryIds: [30, 31, 32],
    titleKey: "admin.danh_sch_ram",
    titleDefault: "RAM",
    searchPlaceholderKey: "admin.tm_kim_ram",
    searchPlaceholderDefault: "Tim RAM...",
    emptyKey: "admin.khng_tm_thy_ram",
    emptyDefault: "Khong co RAM",
    noMatchKey: "remaining.no_ram_match",
    noMatchDefault: "Khong khop",
    formAddTitleKey: "admin.ram_add",
    formAddTitleDefault: "Them RAM",
    formEditTitleKey: "admin.ram_edit",
    formEditTitleDefault: "Sua RAM",
  },
  storage: {
    categoryKey: "storage",
    itemsPropName: "storage",
    activeMenuValue: "Storage",
    categoryBrandMapping: { 27: "Kingston", 28: "Samsung", 29: "Western Digital" },
    validCategoryIds: [27, 28, 29],
    titleKey: "admin.danh_sch_thit_b",
    titleDefault: "O cung / SSD",
    searchPlaceholderKey: "admin.tm_kim_thit_b",
    searchPlaceholderDefault: "Tim thiet bi luu tru...",
    emptyKey: "admin.khng_tm_thy_thit",
    emptyDefault: "Khong co thiet bi",
    noMatchKey: "remaining.no_storage_match",
    noMatchDefault: "Khong khop",
    formAddTitleKey: "admin.storage_add",
    formAddTitleDefault: "Them storage",
    formEditTitleKey: "admin.storage_edit",
    formEditTitleDefault: "Sua storage",
  },
  cases: {
    categoryKey: "case",
    itemsPropName: "cases",
    activeMenuValue: "Case",
    categoryBrandMapping: { 17: "Case" },
    validCategoryIds: [17],
    titleKey: "admin.danh_sch_v_my",
    titleDefault: "Case",
    searchPlaceholderKey: "admin.tm_kim_v_my",
    searchPlaceholderDefault: "Tim case...",
    emptyKey: "admin.khng_tm_thy_v",
    emptyDefault: "Khong co case",
    noMatchKey: "remaining.khong_tim_thay_vo_may_tinh_phu_hop",
    noMatchDefault: "Khong khop",
    formAddTitleKey: "admin.case_add",
    formAddTitleDefault: "Them vo may",
    formEditTitleKey: "admin.case_edit",
    formEditTitleDefault: "Sua vo may",
  },
  mainboards: {
    categoryKey: "mainboard",
    itemsPropName: "mainboards",
    activeMenuValue: "Mainboard",
    categoryBrandMapping: { 20: "Asus", 21: "Gigabyte", 22: "MSI" },
    validCategoryIds: [20, 21, 22],
    titleKey: "admin.danh_sch_bo_mch",
    titleDefault: "Mainboard",
    searchPlaceholderKey: "admin.tm_kim_bo_mch",
    searchPlaceholderDefault: "Tim mainboard...",
    emptyKey: "admin.khng_tm_thy_bo",
    emptyDefault: "Khong co mainboard",
    noMatchKey: "remaining.no_mainboard_match",
    noMatchDefault: "Khong khop",
    formAddTitleKey: "admin.mainboard_add",
    formAddTitleDefault: "Them mainboard",
    formEditTitleKey: "admin.mainboard_edit",
    formEditTitleDefault: "Sua mainboard",
  },
  psus: {
    categoryKey: "psu",
    itemsPropName: "psus",
    activeMenuValue: "Psu",
    categoryBrandMapping: { 23: "Asus", 24: "Corsair", 25: "Deepcool", 26: "MSI" },
    validCategoryIds: [23, 24, 25, 26],
    titleKey: "admin.danh_sch_ngun_my",
    titleDefault: "PSU",
    searchPlaceholderKey: "admin.tm_kim_ngun_my",
    searchPlaceholderDefault: "Tim PSU...",
    emptyKey: "admin.khng_tm_thy_ngun",
    emptyDefault: "Khong co PSU",
    noMatchKey: "remaining.no_psu_match",
    noMatchDefault: "Khong khop",
    formAddTitleKey: "admin.psu_add",
    formAddTitleDefault: "Them PSU",
    formEditTitleKey: "admin.psu_edit",
    formEditTitleDefault: "Sua PSU",
  },
  pcs: {
    categoryKey: "pc",
    itemsPropName: "pcs",
    activeMenuValue: "PC",
    categoryBrandMapping: { 40: "MSI", 41: "ASUS" },
    validCategoryIds: [40, 41],
    titleKey: "admin.danh_sch_pc",
    titleDefault: "PC",
    searchPlaceholderKey: "admin.tm_kim_pc",
    searchPlaceholderDefault: "Tim PC...",
    emptyKey: "admin.khng_tm_thy_pc",
    emptyDefault: "Khong co PC",
    noMatchKey: "remaining.no_pc_match",
    noMatchDefault: "Khong khop",
    formAddTitleKey: "admin.pc_add",
    formAddTitleDefault: "Them PC",
    formEditTitleKey: "admin.pc_edit",
    formEditTitleDefault: "Sua PC",
  },
  headphones: {
    categoryKey: "headphone",
    itemsPropName: "headphones",
    activeMenuValue: "Headphone",
    categoryBrandMapping: { 42: "ASUS", 43: "Razer" },
    validCategoryIds: [42, 43],
    titleKey: "admin.danh_sch_tai_nghe",
    titleDefault: "Tai nghe",
    searchPlaceholderKey: "admin.tm_kim_tai_nghe",
    searchPlaceholderDefault: "Tim tai nghe...",
    emptyKey: "admin.khng_tm_thy_tai",
    emptyDefault: "Khong co tai nghe",
    noMatchKey: "remaining.no_headphone_match",
    noMatchDefault: "Khong khop",
    formAddTitleKey: "admin.headphone_add",
    formAddTitleDefault: "Them tai nghe",
    formEditTitleKey: "admin.headphone_edit",
    formEditTitleDefault: "Sua tai nghe",
  },
  mousepads: {
    categoryKey: "mousepad",
    itemsPropName: "mousepads",
    activeMenuValue: "Mousepad",
    categoryBrandMapping: { 11: "Daeru", 12: "ASUS", 13: "Razer" },
    validCategoryIds: [11, 12, 13],
    titleKey: "admin.danh_sch_bn_di",
    titleDefault: "Mousepad",
    searchPlaceholderKey: "admin.tm_kim_bn_di",
    searchPlaceholderDefault: "Tim mousepad...",
    emptyKey: "remaining.no_mousepad_found",
    emptyDefault: "Khong co mousepad",
    noMatchKey: "remaining.no_mousepad_match",
    noMatchDefault: "Khong khop",
    formAddTitleKey: "admin.mousepad_add",
    formAddTitleDefault: "Them mousepad",
    formEditTitleKey: "admin.mousepad_edit",
    formEditTitleDefault: "Sua mousepad",
  },
  tablets: {
    categoryKey: "tablet",
    itemsPropName: "tablets",
    activeMenuValue: "Tablet",
    categoryBrandMapping: { 44: "Apple" },
    validCategoryIds: [44],
    titleKey: "admin.tablet_list_title",
    titleDefault: "Tablet",
    searchPlaceholderKey: "admin.tablet_search_placeholder",
    searchPlaceholderDefault: "Tim tablet...",
    emptyKey: "remaining.no_tablet_found",
    emptyDefault: "Khong co tablet",
    noMatchKey: "remaining.no_tablet_match",
    noMatchDefault: "Khong khop",
    formAddTitleKey: "admin.tablet_add",
    formAddTitleDefault: "Them tablet",
    formEditTitleKey: "admin.tablet_edit",
    formEditTitleDefault: "Sua tablet",
  },
  keyboards: {
    categoryKey: "keyboard",
    itemsPropName: "keyboards",
    activeMenuValue: "KeyBoard",
    categoryBrandMapping: { 1: "AKKO", 2: "Logitech", 3: "Razer", 4: "Dareu", 5: "Asus" },
    validCategoryIds: [1, 2, 3, 4, 5],
    titleKey: "admin.danh_sch_bn_phm",
    titleDefault: "Keyboard",
    searchPlaceholderKey: "admin.tm_kim_bn_phm",
    searchPlaceholderDefault: "Tim ban phim...",
    emptyKey: "admin.khng_tm_thy_bn",
    emptyDefault: "Khong co ban phim",
    noMatchKey: "remaining.no_keyboard_match",
    noMatchDefault: "Khong khop",
    formAddTitleKey: "admin.keyboard_add",
    formAddTitleDefault: "Them ban phim",
    formEditTitleKey: "admin.keyboard_edit",
    formEditTitleDefault: "Sua ban phim",
  },
  mouses: {
    categoryKey: "mouse",
    itemsPropName: "mouses",
    activeMenuValue: "Mouse",
    categoryBrandMapping: { 6: "Dareu", 7: "MSI", 8: "Logitech", 9: "Rapoo", 10: "Razer" },
    validCategoryIds: [6, 7, 8, 9, 10],
    titleKey: "admin.danh_sch_chut",
    titleDefault: "Mouse",
    searchPlaceholderKey: "admin.tm_kim_chut",
    searchPlaceholderDefault: "Tim chuot...",
    emptyKey: "admin.khng_tm_thy_chut",
    emptyDefault: "Khong co chuot",
    noMatchKey: "remaining.no_mouse_match",
    noMatchDefault: "Khong khop",
    formAddTitleKey: "admin.mouse_add",
    formAddTitleDefault: "Them chuot",
    formEditTitleKey: "admin.mouse_edit",
    formEditTitleDefault: "Sua chuot",
  },
  monitors: {
    categoryKey: "computers",
    itemsPropName: "monitors",
    activeMenuValue: "Computers",
    categoryBrandMapping: { 36: "ASUS", 37: "Acer", 38: "LG", 39: "MSI" },
    validCategoryIds: [36, 37, 38, 39],
    titleKey: "admin.danh_sch_mn_hnh",
    titleDefault: "Monitors",
    searchPlaceholderKey: "admin.tm_kim_mn_hnh",
    searchPlaceholderDefault: "Tim man hinh...",
    emptyKey: "admin.khng_tm_thy_mn",
    emptyDefault: "Khong co man hinh",
    noMatchKey: "remaining.no_monitor_match",
    noMatchDefault: "Khong khop",
    formAddTitleKey: "admin.monitor_add",
    formAddTitleDefault: "Them man hinh",
    formEditTitleKey: "admin.monitor_edit",
    formEditTitleDefault: "Sua man hinh",
  },
  computers: {
    categoryKey: "computers",
    itemsPropName: "monitors",
    activeMenuValue: "Computers",
    categoryBrandMapping: { 36: "ASUS", 37: "Acer", 38: "LG", 39: "MSI" },
    validCategoryIds: [36, 37, 38, 39],
    titleKey: "admin.danh_sch_mn_hnh",
    titleDefault: "Monitors",
    searchPlaceholderKey: "admin.tm_kim_mn_hnh",
    searchPlaceholderDefault: "Tim man hinh...",
    emptyKey: "admin.khng_tm_thy_mn",
    emptyDefault: "Khong co man hinh",
    noMatchKey: "remaining.no_monitor_match",
    noMatchDefault: "Khong khop",
    formAddTitleKey: "admin.monitor_add",
    formAddTitleDefault: "Them man hinh",
    formEditTitleKey: "admin.monitor_edit",
    formEditTitleDefault: "Sua man hinh",
  },
  gaminggear: {
    categoryKey: "gamingGear",
    itemsPropName: "gamingGear",
    activeMenuValue: "GamingGear",
    categoryBrandMapping: { 14: "Sony", 15: "Lenovo", 16: "Daeru" },
    validCategoryIds: [14, 15, 16],
    titleKey: "admin.danh_sch_gaming_gear",
    titleDefault: "Gaming Gear",
    searchPlaceholderKey: "admin.tm_kim_gaming_gear",
    searchPlaceholderDefault: "Tim gaming gear...",
    emptyKey: "admin.khng_tm_thy_gaming",
    emptyDefault: "Khong co gaming gear",
    noMatchKey: "remaining.khong_tim_thay_gaming_gear_phu_hop",
    noMatchDefault: "Khong khop",
    formAddTitleKey: "admin.gaming_gear_add",
    formAddTitleDefault: "Them gaming gear",
    formEditTitleKey: "admin.gaming_gear_edit",
    formEditTitleDefault: "Sua gaming gear",
  },
};

export default function StockProductPage() {
  const { t } = useTranslation();
  const { category } = useParams();
  const config = CATEGORY_CONFIG[category];
  const { items, parentLoading, createProduct, updateProduct } = useStockProductRouteProps(
    config?.categoryKey || "",
    {},
    config?.itemsPropName || "items",
  );

  if (!config) {
    return (
      <div className="p-8 text-center text-[var(--color-text-muted)]">
        Category not found
      </div>
    );
  }

  return (
    <StockProductAdminSection
      activeMenuValue={config.activeMenuValue}
      items={items}
      parentLoading={parentLoading}
      createProduct={createProduct}
      updateProduct={updateProduct}
      categoryBrandMapping={config.categoryBrandMapping}
      validCategoryIds={config.validCategoryIds}
      titleKey={config.titleKey}
      titleDefault={config.titleDefault}
      searchPlaceholderKey={config.searchPlaceholderKey}
      searchPlaceholderDefault={config.searchPlaceholderDefault}
      emptyKey={config.emptyKey}
      emptyDefault={config.emptyDefault}
      noMatchKey={config.noMatchKey}
      noMatchDefault={config.noMatchDefault}
      formAddTitle={t(config.formAddTitleKey, config.formAddTitleDefault)}
      formEditTitle={t(config.formEditTitleKey, config.formEditTitleDefault)}
    />
  );
}
